# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e532c439de47c49a926345d056ec91a3dacefe8876c2592466e312a7d64450318d9b5d10af93bef16e203d77fa70c1fd2a3746b22af97c80cb1e330ab9bcf435

test:
  secret_key_base: 7ea9aa51a8239003cf8c344639139556386bb7b25597583ca6d0214759f89c56af88060cabce4cf25a9f94118d640ecbebadbd9e1cb274ae5b62bb1cd558a31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
